platform :ios,"9.0"
use_frameworks!

target ‘KevinDemo’ do
    
    post_install do |installer|
        # 需要指定编译版本的第三方的名称
        myTargets = ['CLImagePickerTool']
        
        installer.pods_project.targets.each do |target|
            if myTargets.include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
    
    pod 'MJRefresh'            #下拉刷新
    pod 'Alamofire', '~> 4.7'  #网络请求
    pod 'BlocksKit'            #将delegate转换为block的库
    pod 'IQKeyboardManagerSwift' #使用iQ键盘
    pod 'MBProgressHUD'          #遮罩
    pod 'FMDB'
    pod 'SSZipArchive'
    pod 'SDCycleScrollView', '~> 1.65'
    pod 'AliyunOSSiOS', '~> 2.6.0'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDWebImage'           #图片离线缓存类
    pod 'AWSS3', '~> 2.6.0'    #AWSS3上传下载
    pod 'SnapKit', '~> 4.0.0'   #autolayout
    pod 'ObjectMapper', '~> 3.1'   #json 转模型
    pod 'IQActionSheetPickerView', '~>2.0.0'  #picker选择器
    pod 'CLImagePickerTool'
    pod 'UITextView+Placeholder', '~> 1.2'
    pod 'SKPhotoBrowser'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Toast', '~> 3.0'
    pod 'M80AttributedLabel', '~> 1.6.3'
    pod 'TZImagePickerController', '~> 1.9.3'
    pod 'NIMSDK_LITE'
    pod 'PopupDialog', '~> 0.7'
    pod 'Closures'
#    pod 'FacebookSDK'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKPlacesKit'
    pod 'FBSDKMessengerShareKit'
end




